### ISSUE TITLE
Les partenaires

### ISSUE THREAD

**Issue by toomanyMG** [WildCodeSchool/2022-09-php-orleans-project-ecurieorleans#286]
Faites attention ici, pas besoin de placeholder pour les partenaires, ils ont leur propres logo.
Et si il y n'y a pas de partenaire pas besoin d'afficher quoi que ce soit.

<img width="1387" alt="Capture d’écran 2022-11-22 à 15 02 11" src="https://user-images.githubusercontent.com/89526810/203333303-096462fa-b571-49b1-bfde-3216442cf73d.png">

**Comment by NefytZ** [comment]
je ne suis pas d'accord sur ce point.
à la presentation du site au client il faut obligatoirement montrer le rendu de la page avec des partenaires fictifs, car on ne laisse pas place a l'imagination il faut voir le rendu.
et impossible de ne pas rendre null les photos car pour les afficher il faudrait qu'elle soit dans le dossier Upload :) donc le choix du place holder est le plus judicieux.
