### ISSUE TITLE
Spacing form /admin

### ISSUE THREAD

**Issue by toomanyMG** [WildCodeSchool/2022-09-php-orleans-project-ecurieorleans#288]
Faites attention quand il y a une erreur sur le form il ce plaquer en fin de page sans spacing.

<img width="1387" alt="Capture d’écran 2022-11-22 à 15 10 57" src="https://user-images.githubusercontent.com/89526810/203335609-f03112df-5d71-42ab-abfb-b0b216002168.png">

**Comment by V-Gillet** [comment]
J'ai le problème sur aucun de mes écrans mdr. Ca doit être un truc d'écran Rétina :p
